// Source: SkrGuiCore/text/font_face.hpp @ 611561f8.
namespace SkrGui;

public abstract partial class FontFace
{
    public abstract bool IsValid();
    public abstract TextFontFaceId Id();
    public abstract FontProvider Provider();
    public abstract ref readonly FontProviderFaceSource Source();
    public abstract uint FaceIndex();
    public abstract bool SetFaceIndex(uint value);
    public abstract uint FaceCount();
    public abstract Utf8StringView FamilyName();
    public abstract void SetFamilyName(Utf8StringView value);
    public abstract Utf8StringView StyleName();
    public abstract void SetStyleName(Utf8StringView value);
    public abstract EFontWeight Weight();
    public abstract void SetWeight(EFontWeight value);
    public abstract EFontStyle Style();
    public abstract void SetStyle(EFontStyle value);
    public abstract EFontStretch Stretch();
    public abstract void SetStretch(EFontStretch value);
    public abstract bool IsFixedWidth();
    public abstract ReadOnlySpan<FontOpenTypeName> OpenTypeNames();
    public abstract ReadOnlySpan<FontVariationAxis> VariationAxes();
    public abstract ReadOnlySpan<FontVariationCoordinate> VariationCoordinates();
    public abstract bool SetVariationCoordinates(ReadOnlySpan<FontVariationCoordinate> coordinates);
    public abstract ReadOnlySpan<FontOpenTypeFeature> OpenTypeFeatures();
    public abstract ReadOnlySpan<FontOpenTypeFeatureValue> OpenTypeFeatureOverrides();
    public abstract void SetOpenTypeFeatureOverrides(ReadOnlySpan<FontOpenTypeFeatureValue> overrides);
    public abstract bool IsLanguageSupported(Utf8StringView language);
    public abstract bool LanguageSupportOverride(Utf8StringView language);
    public abstract void SetLanguageSupportOverride(Utf8StringView language, bool supported);
    public abstract void RemoveLanguageSupportOverride(Utf8StringView language);
    public abstract void LanguageSupportOverrides(List<Utf8StringView> out_languages);
    public abstract bool IsScriptSupported(Utf8StringView script);
    public abstract bool ScriptSupportOverride(Utf8StringView script);
    public abstract void SetScriptSupportOverride(Utf8StringView script, bool supported);
    public abstract void RemoveScriptSupportOverride(Utf8StringView script);
    public abstract void ScriptSupportOverrides(List<Utf8StringView> out_scripts);
    public abstract bool HasCodepoint(uint codepoint);
    public abstract uint GlyphIndex(uint codepoint, uint variation_selector = 0);
    public abstract uint CodepointFromGlyphIndex(uint glyph_index);
    public abstract void SupportedCodepoints(List<uint> out_codepoints);
    public abstract void SupportedGlyphs(List<uint> out_glyphs);
    public abstract Offsetf GlyphAdvance(uint glyph_index, float font_size);
    public abstract Offsetf GlyphOffset(uint glyph_index, float font_size);
    public abstract Sizef GlyphSize(uint glyph_index, float font_size);
    public abstract Offsetf Kerning(uint left_glyph, uint right_glyph, float font_size);
    public abstract bool GlyphContour(uint glyph_index, float font_size, VGPath out_path);
    public abstract FontFaceMetrics Metrics(float font_size);
    public abstract bool HasColorGlyphs();
    public abstract uint PaletteCount();
    public abstract Utf8StringView PaletteName(uint index);
    public abstract ReadOnlySpan<SRGBColor> PaletteColors(uint index);
    public abstract uint UsedPalette();
    public abstract bool SetUsedPalette(uint index);
    public abstract ReadOnlySpan<SRGBColor> CustomPaletteColors();
    public abstract void SetCustomPaletteColors(ReadOnlySpan<SRGBColor> colors);
    public abstract float Embolden();
    public abstract void SetEmbolden(float value);
    public abstract float Spacing(ETextSpacing type);
    public abstract void SetSpacing(ETextSpacing type, float value);
    public abstract float BaselineOffset();
    public abstract void SetBaselineOffset(float value);
    public abstract Float3x3 Transform();
    public abstract void SetTransform(Float3x3 value);
    public abstract void SetMetrics(float font_size, FontFaceMetrics metrics);
    public abstract void SetGlyphAdvance(uint glyph_index, float font_size, Offsetf advance);
    public abstract void ClearGlyphs(float font_size);
    public abstract void RemoveGlyph(uint glyph_index, float font_size);
    public abstract void SetGlyphOffset(uint glyph_index, float font_size, Offsetf value);
    public abstract void SetGlyphSize(uint glyph_index, float font_size, Sizef value);
    public abstract void SetKerning(uint left_glyph, uint right_glyph, float font_size, Offsetf value);
}
