// Source: SkrGuiCore/text/text_paragraph.hpp @ 611561f8.
namespace SkrGui;

public abstract partial class TextParagraph
{
    public abstract void Clear();
    public abstract TextParagraph Duplicate();
    public abstract TextLayoutSpanId AddString(Utf8StringView text, TextStyle style, Utf8StringView language = default);
    public abstract bool AddObject(ulong key, Sizef size, ETextInlineAlignment inline_align = ETextInlineAlignment.Center, ulong length = 1, float baseline = 0.0f);
    public abstract bool ResizeObject(ulong key, Sizef size, ETextInlineAlignment inline_align = ETextInlineAlignment.Center, float baseline = 0.0f);
    public abstract bool HasObject(ulong key);
    public abstract Utf8StringView Text();
    public abstract TextRange SourceRange();
    public abstract ulong SpanCount();
    public abstract TextLayoutSpanId SpanId(ulong index);
    public abstract Utf8StringView SpanText(TextLayoutSpanId id);
    public abstract ReadOnlyTextStyle? SpanStyle(TextLayoutSpanId id);
    public abstract Utf8StringView SpanLanguage(TextLayoutSpanId id);
    public abstract bool SpanEmbeddedObject(TextLayoutSpanId id, ref ulong out_key);
    public abstract bool UpdateSpanStyle(TextLayoutSpanId id, TextStyle style);
    public abstract ulong ObjectCount();
    public abstract ulong ObjectKey(ulong index);
    public abstract TextRange ObjectRange(ulong key);
    public abstract long ObjectGlyphIndex(ulong key);
    public abstract Rectf ObjectRect(ulong key);
    public abstract void SetDirection(ETextDirectionMode value);
    public abstract ETextDirectionMode Direction();
    public abstract ETextDirection InferredDirection();
    public abstract void SetBidiOverride(ReadOnlySpan<TextBidiOverride> overrides);
    public abstract void SetOrientation(ETextOrientation value);
    public abstract ETextOrientation Orientation();
    public abstract void SetPreserveInvalid(bool value);
    public abstract bool PreserveInvalid();
    public abstract void SetPreserveControl(bool value);
    public abstract bool PreserveControl();
    public abstract void SetCustomPunctuation(Utf8StringView punctuation);
    public abstract Utf8StringView CustomPunctuation();
    public abstract void SetMaxWidth(float value);
    public abstract float MaxWidth();
    public abstract void SetMaxLinesVisible(int value);
    public abstract int MaxLinesVisible();
    public abstract void SetLineSpacing(float value);
    public abstract float LineSpacing();
    public abstract void SetAlignment(ETextHAlign value);
    public abstract ETextHAlign Alignment();
    public abstract void SetBreakFlags(ETextLineBreakFlag value);
    public abstract ETextLineBreakFlag BreakFlags();
    public abstract void SetJustificationFlags(ETextJustificationFlag value);
    public abstract ETextJustificationFlag JustificationFlags();
    public abstract void SetTextOverrunBehavior(ETextOverrunBehavior value);
    public abstract ETextOverrunBehavior TextOverrunBehavior();
    public abstract void SetEllipsisCodepoint(uint value);
    public abstract uint EllipsisCodepoint();
    public abstract void SetSpacing(ETextSpacing type, float value);
    public abstract float Spacing(ETextSpacing type);
    public abstract float TabAlign(ReadOnlySpan<float> tab_stops);
    public abstract bool Shape();
    public abstract bool IsReady();
    public abstract ulong GlyphCount();
    public abstract ReadOnlySpan<TextGlyph> Glyphs();
    public abstract ReadOnlySpan<TextGlyph> SortLogicalGlyphs();
    public abstract ulong VisibleCharacters();
    public abstract ulong TrimPosition();
    public abstract ulong EllipsisPosition();
    public abstract ReadOnlySpan<TextGlyph> EllipsisGlyphs();
    public abstract ulong EllipsisGlyphCount();
    public abstract Sizef NonWrappedSize();
    public abstract Sizef Size();
    public abstract ulong RunCount();
    public abstract Utf8StringView RunText(ulong index);
    public abstract TextRange RunSourceRange(ulong index);
    public abstract TextRange RunGlyphRange(ulong index);
    public abstract FontFace? RunFontFace(ulong index);
    public abstract float RunFontSize(ulong index);
    public abstract Utf8StringView RunLanguage(ulong index);
    public abstract ETextDirection RunDirection(ulong index);
    public abstract bool RunObject(ulong index, ref ulong out_key);
    public abstract TextLayoutSpanId RunSpanId(ulong index);
    public abstract ulong LineCount();
    public abstract Sizef LineSize(ulong line);
    public abstract float LineWidth(ulong line);
    public abstract float LineAscent(ulong line);
    public abstract float LineDescent(ulong line);
    public abstract TextRange LineRange(ulong line);
    public abstract TextRange LineGlyphRange(ulong line);
    public abstract bool LineObjects(ulong line, List<ulong> out_keys);
    public abstract Rectf LineObjectRect(ulong line, ulong key);
    public abstract float LineUnderlinePosition(ulong line);
    public abstract float LineUnderlineThickness(ulong line);
    public abstract bool LineBreaks(float width, ulong start, ETextLineBreakFlag flags, List<TextRange> out_ranges);
    public abstract bool LineBreaks(ReadOnlySpan<float> widths, ulong start, bool once, ETextLineBreakFlag flags, List<TextRange> out_ranges);
    public abstract bool WordBreaks(ETextGraphemeFlag grapheme_flags, ETextGraphemeFlag skip_grapheme_flags, List<TextRange> out_ranges);
    public abstract float FitToWidth(float width, ETextJustificationFlag flags = TextDefaults.JustificationFlags);
    public abstract void OverrunTrimToWidth(float width, ETextOverrunFlag flags);
    public abstract TextParagraph? Substring(TextRange range);
    public abstract long HitTestPosition(Offsetf coords);
    public abstract long HitTestGrapheme(Offsetf coords);
    public abstract TextCaretInfo Caret(ulong position);
    public abstract bool SelectionRects(TextRange range, List<Rectf> out_rects);
    public abstract TextFloatRange GraphemeBounds(ulong position);
    public abstract long PreviousGraphemePosition(ulong position);
    public abstract long NextGraphemePosition(ulong position);
    public abstract bool CharacterBreaks(List<ulong> out_breaks);
    public abstract long PreviousCharacterPosition(ulong position);
    public abstract long NextCharacterPosition(ulong position);
    public abstract long ClosestCharacterPosition(ulong position);
    public abstract ETextDirection RangeDirection(TextRange range);
    public abstract void SetDropCap(Utf8StringView text, TextStyle style, uint lines, Rectf margins = default, Utf8StringView language = default);
    public abstract void ClearDropCap();
    public abstract uint DropCapLines();
    public abstract Sizef DropCapSize();
    public abstract ReadOnlySpan<TextGlyph> DropCapGlyphs();
    public abstract bool PaintDropCap(Offsetf origin, TextRenderResult out_result, TextPaintDesc? desc = null);
    public abstract bool Paint(Offsetf origin, TextRenderResult out_result, TextPaintDesc? desc = null);
    public abstract bool PaintLine(ulong line, Offsetf origin, TextRenderResult out_result, TextPaintDesc? desc = null);
}
