from pathlib import Path
base=Path('libraries/SkrGui.Core')
p=base/'Math/Layout/Placement.cs';s=p.read_text().replace('out result.MinWidth,out result.MaxWidth','ref result.MinWidth,ref result.MaxWidth').replace('out result.MinHeight,out result.MaxHeight','ref result.MinHeight,ref result.MaxHeight').replace('out float resultMin,out float resultMax','ref float resultMin,ref float resultMax').replace('        resultMin=resultMax=0;\n','');p.write_text(s)
p=base/'Visual/VisualHitTest.cs';s=p.read_text().replace('Path()=>_path','Path()=>_path.AsReadOnly()').replace('if(!TryInvert(RemovePerspectiveTransform(transform.Value),out var raw))','Matrix4x4 raw=new();\n        if(!TryInvert(RemovePerspectiveTransform(transform.Value),ref raw))').replace('if(!ProjectPosition(transform.Value,position,out var transformedPosition))','Offsetf transformedPosition=new();\n        if(!ProjectPosition(transform.Value,position,ref transformedPosition))').replace('out Matrix4x4 inverse)','ref Matrix4x4 inverse)').replace('float determinant=transform.GetDeterminant(); inverse=new();','float determinant=transform.GetDeterminant();').replace('out Offsetf result)','ref Offsetf result)').replace('        result=new(); if(!float.IsFinite(point.X)','        if(!float.IsFinite(point.X)');p.write_text(s)
p=base/'Visual/MultiChild/VisualWrap.cs';s=p.read_text().replace('out ulong index){index=0;','ref ulong index){').replace('NextChildIndex(index,mainFlipped,out index)','NextChildIndex(index,mainFlipped,ref index)');p.write_text(s)
p=base/'Visual/MultiChild/VisualGrid.cs';s=p.read_text().replace('Columns()=>_columns','Columns()=>_columns.AsReadOnly()').replace('Rows()=>_rows','Rows()=>_rows.AsReadOnly()');p.write_text(s)
p=base/'Visual/Proxy/VisualTransform.cs';s=p.read_text().replace('public PaintTransform Transform()=>_transform;', 'public ref readonly PaintTransform Transform()=>ref _transform;');p.write_text(s)
p=base/'Visual/MultiChild/VisualPlacement.cs';s=p.read_text().replace('public Placement Placement()=>_placement;', 'public ref readonly Placement Placement()=>ref _placement;');p.write_text(s)
p=base/'Math/M3/M3TonalPalette.cs';s=p.read_text().replace('namespace SkrGui;','using System.Diagnostics.CodeAnalysis;\nnamespace SkrGui;').replace('public HCTColor KeyColor()','[UnscopedRef] public ref readonly HCTColor KeyColor()').replace('return _key_color;','return ref _key_color;');p.write_text(s)
