from pathlib import Path
p=Path('libraries/SkrGui.Core/Text/Font/FilesFontProvider.cs');s=p.read_text()
s=s.replace('List<string> Families','List<Utf8StringView> Families').replace('LiveReadOnlyList<string>','LiveReadOnlyList<Utf8StringView>').replace('IReadOnlyList<string> Families','IReadOnlyList<Utf8StringView> Families')
s=s.replace('HasFamily(string family)','HasFamily(Utf8StringView family)')
s=s.replace('out string value','out Utf8StringView value').replace('ref string value','ref Utf8StringView value')
s=s.replace('value=new string(chars);return value.Length!=0;', 'value=new string(chars);return !value.IsEmpty();')
s=s.replace('value=Encoding.ASCII.GetString(data.Slice((int)offset,size));return value.Length!=0;', 'value=new Utf8StringView(data.Slice((int)offset,size).ToArray());return !value.IsEmpty();')
s=s.replace('List<string> families,string family','List<Utf8StringView> families,Utf8StringView family').replace('List<string> families','List<Utf8StringView> families').replace('family.Length==0','family.IsEmpty()').replace('families.Add(family);','families.Add(new Utf8StringView(family.Bytes.ToArray()));')
s=s.replace('string family="";', 'Utf8StringView family="";')
s=s.replace('ParseFace(string path,','ParseFace(Utf8StringView path,').replace('ParseFile(string path,','ParseFile(Utf8StringView path,')
s=s.replace('SourceKey=path,FaceIndex=index','SourceKey=new Utf8StringView(path.Bytes.ToArray()),FaceIndex=index')
s=s.replace('List<string> _fontPaths','List<Utf8StringView> _fontPaths')
s=s.replace('internal static string FilesFontSourceKey(string path)','internal static Utf8StringView FilesFontSourceKey(Utf8StringView path)')
s=s.replace('new FileInfo(path)','new FileInfo(path.ToString())')
s=s.replace('return FormattableString.Invariant($"{path}#skr-font:{stamp}:{f.Length}");', '''byte[] suffix=Encoding.ASCII.GetBytes(FormattableString.Invariant($"#skr-font:{stamp}:{f.Length}"));
            byte[] key=new byte[path.Bytes.Length+suffix.Length];path.Bytes.CopyTo(key);suffix.CopyTo(key,path.Bytes.Length);
            return new Utf8StringView(key);''')
s=s.replace('public bool AddFontFile(string path)','public bool AddFontFile(Utf8StringView path)')
s=s.replace('_fontPaths.Add(path);','_fontPaths.Add(new Utf8StringView(path.Bytes.ToArray()));')
s=s.replace('AddFontFiles(ReadOnlySpan<string> paths)','AddFontFiles(ReadOnlySpan<Utf8StringView> paths)')
s=s.replace('QueryFace(string family,','QueryFace(Utf8StringView family,')
s=s.replace('foreach(string path in _fontPaths)','foreach(Utf8StringView path in _fontPaths)')
s=s.replace('private static bool ReadAll(string path,','private static bool ReadAll(Utf8StringView path,')
s=s.replace('File.ReadAllBytes(path)','File.ReadAllBytes(path.ToString())')
s=s.replace('result.Families.AddRange(f.Families);', 'foreach(var family in f.Families)result.Families.Add(new Utf8StringView(family.Bytes.ToArray()));')
p.write_text(s)
p=Path('tests/SkrGui.Core.Tests/Text/FilesFontSourceContractTests.cs');s=p.read_text().replace('string value="sentinel";','Utf8StringView value="sentinel";').replace('Check.Equal("sentinel",value)','Check.Equal((Utf8StringView)"sentinel",value)').replace('Check.Equal("",value)','Check.Equal((Utf8StringView)"",value)').replace('families is IList<string>','families is IList<Utf8StringView>').replace('Check.Equal(path,borrowed.Source.SourceKey)','Check.Equal((Utf8StringView)path,borrowed.Source.SourceKey)');p.write_text(s)
