"""Mechanical expansion of the explicitly reviewed f/i SkrGui geometry pairs.
This emits source-equivalent operators; it does not select new algorithms.
"""
from pathlib import Path

root = Path(__file__).resolve().parents[1] / 'libraries/SkrGui.Core/Math/Geometry'
root.mkdir(parents=True, exist_ok=True)
for suffix, scalar in [('f','float'),('i','int')]:
    for kind, a, b in [('Offset','X','Y'), ('Size','Width','Height')]:
        t = kind + suffix
        offset = 'Offset'+suffix
        lines = ['namespace SkrGui;', '', f'// Source: SkrGuiCore/math/geometry/{kind.lower()}.hpp (611561f8).', f'public partial struct {t} : IEquatable<{t}>', '{', f'    public {scalar} {a}, {b};', f'    public {t}({scalar} {a.lower()}, {scalar} {b.lower()}) {{ {a}={a.lower()}; {b}={b.lower()}; }}', f'    public static {t} Zero() => new(0,0);']
        if kind=='Offset':
            lines += [f'    public static {t} operator-({t} value) => new(-value.X,-value.Y);']
        for op in ['+','-','*','/','%']:
            for lhs, rhs in [(t,t),(t,scalar),(scalar,t)]:
                x1='lhs.'+a if lhs==t else 'lhs'; y1='lhs.'+b if lhs==t else 'lhs'
                x2='rhs.'+a if rhs==t else 'rhs'; y2='rhs.'+b if rhs==t else 'rhs'
                lines += [f'    public static {t} operator{op}({lhs} lhs, {rhs} rhs) => new({x1}{op}{x2},{y1}{op}{y2});']
        lines += [f'    public static bool operator==({t} lhs,{t} rhs) => lhs.{a}==rhs.{a} && lhs.{b}==rhs.{b};', f'    public static bool operator!=({t} lhs,{t} rhs) => !(lhs==rhs);', f'    public bool Equals({t} rhs) => this==rhs;', f'    public override bool Equals(object? obj) => obj is {t} rhs && this==rhs;', f'    public override int GetHashCode() => HashCode.Combine({a},{b});']
        other=kind+('i' if suffix=='f' else 'f')
        cast='int' if suffix=='f' else 'float'
        lines += [f'    public static implicit operator {other}({t} v) => new(({cast})v.{a},({cast})v.{b});']
        if kind=='Size':
            lines += [f'    public static {t} Square({scalar} size) => new(size,size);',f'    public static {t} Radius({scalar} radius) => new(radius*2,radius*2);',f'    public bool IsEmpty() => Width<=0 || Height<=0;',f'    public {scalar} Area() => '+('IsFinite() ? MathF.Abs(Width*Height) : float.PositiveInfinity;' if suffix=='f' else 'Math.Abs(Width*Height);'),f'    public {scalar} ShortestSide() => CppMath.Min(Math.Abs(Width),Math.Abs(Height));',f'    public {scalar} LongestSide() => CppMath.Max(Math.Abs(Width),Math.Abs(Height));', f'    public {t} Flipped() => new(Height,Width);',f'    public bool Contains({offset} p) => p.X>=0 && p.X<=Width && p.Y>=0 && p.Y<=Height;',f'    public static {t} Min({t} a,{t} b) => new(CppMath.Min(a.Width,b.Width),CppMath.Min(a.Height,b.Height));',f'    public static {t} Max({t} a,{t} b) => new(CppMath.Max(a.Width,b.Width),CppMath.Max(a.Height,b.Height));']
            for name,x,y in [('TopLeft','0','0'),('TopCenter','Width/2','0'),('TopRight','Width','0'),('CenterLeft','0','Height/2'),('Center','Width/2','Height/2'),('CenterRight','Width','Height/2'),('BottomLeft','0','Height'),('BottomCenter','Width/2','Height'),('BottomRight','Width','Height')]:
                lines += [f'    public {offset} {name}({offset} offset) => new(offset.X+{x},offset.Y+{y});']
        if suffix=='f':
            lines += [f'    public bool IsFinite() => float.IsFinite({a}) && float.IsFinite({b});',f'    public bool IsInfinite() => {a}>=float.PositiveInfinity || {b}>=float.PositiveInfinity;',f'    public static {t} Infinite() => new(float.PositiveInfinity,float.PositiveInfinity);', f'    public static {t} Lerp({t} a,{t} b,float t) => new(a.{a}+(b.{a}-a.{a})*t,a.{b}+(b.{b}-a.{b})*t);']
            if kind=='Size':
                lines += ['    public static Sizef InfiniteWidth(float height) => new(float.PositiveInfinity,height);','    public static Sizef InfiniteHeight(float width) => new(width,float.PositiveInfinity);','    public float AspectRatio() { if(Height!=0) return Width/Height; if(Width>0) return float.PositiveInfinity; if(Width<0) return float.NegativeInfinity; return 0; }']
            else:
                lines += ['    public static Offsetf Radians(float radians,float radius=1) => new(radius*MathF.Cos(radians),radius*MathF.Sin(radians));','    public bool NearlyEqual(Offsetf rhs,float tolerance) => (this-rhs).LengthSquared() <= tolerance*tolerance;','    public float Length() => MathF.Sqrt(X*X+Y*Y);','    public float LengthSquared() => X*X+Y*Y;','    public float Radians() => MathF.Atan2(Y,X);','    public Offsetf Normalize(Offsetf fallback=default) { float lengthSq=LengthSquared(); if(!float.IsFinite(lengthSq)||lengthSq<=0) return fallback; return this/MathF.Sqrt(lengthSq); }','    public Offsetf CwNormal() => new(-Y,X);','    public Offsetf CcwNormal() => new(Y,-X);','    public float Cross(Offsetf rhs) => X*rhs.Y-Y*rhs.X;','    public float Dot(Offsetf rhs) => X*rhs.X+Y*rhs.Y;']
        lines += ['}', '']
        (root/(t+'.cs')).write_text('\n'.join(lines),encoding='utf-8')
    t='Rect'+suffix; offset='Offset'+suffix; size='Size'+suffix
    lines=['namespace SkrGui;', '', '// Source: SkrGuiCore/math/geometry/rect.hpp (611561f8).',f'public partial struct {t} : IEquatable<{t}>','{',f'    public {scalar} Left,Top,Right,Bottom;',f'    public {t}({scalar} left,{scalar} top,{scalar} right,{scalar} bottom) {{ Left=left; Top=top; Right=right; Bottom=bottom; }}',f'    public static {t} Zero() => new(0,0,0,0);',f'    public static {t} Largest() => new(-1000000000,-1000000000,1000000000,1000000000);',f'    public static {t} LTWH({scalar} left,{scalar} top,{scalar} width,{scalar} height) => new(left,top,left+width,top+height);',f'    public static {t} Circle({offset} center,{scalar} radius) => new(center.X-radius,center.Y-radius,center.X+radius,center.Y+radius);',f'    public static {t} Center({offset} center,{size} size) => new(center.X-size.Width/2,center.Y-size.Height/2,center.X+size.Width/2,center.Y+size.Height/2);',f'    public static {t} OffsetSize({offset} offset,{size} size) => new(offset.X,offset.Y,offset.X+size.Width,offset.Y+size.Height);',f'    public static {t} Points({offset} a,{offset} b) => new(CppMath.Min(a.X,b.X),CppMath.Min(a.Y,b.Y),CppMath.Max(a.X,b.X),CppMath.Max(a.Y,b.Y));',f'    public bool IsEmpty() => Left>=Right || Top>=Bottom;',f'    public bool IsPoint() => Left==Right && Top==Bottom;',f'    public {scalar} Width() => Right-Left;',f'    public {scalar} Height() => Bottom-Top;',f'    public {size} Size() => new(Width(),Height());']
    for name,x,y in [('TopLeft','Left','Top'),('TopCenter','(Left+Right)/2','Top'),('TopRight','Right','Top'),('CenterLeft','Left','(Top+Bottom)/2'),('Center','(Left+Right)/2','(Top+Bottom)/2'),('CenterRight','Right','(Top+Bottom)/2'),('BottomLeft','Left','Bottom'),('BottomCenter','(Left+Right)/2','Bottom'),('BottomRight','Right','Bottom')]: lines += [f'    public {offset} {name}() => new({x},{y});']
    lines += [f'    public {t} Shift({offset} offset) => new(Left+offset.X,Top+offset.Y,Right+offset.X,Bottom+offset.Y);',f'    public {t} Hold({offset} point) => new(CppMath.Min(Left,point.X),CppMath.Min(Top,point.Y),CppMath.Max(Right,point.X),CppMath.Max(Bottom,point.Y));',f'    public {t} Inflate({scalar} delta) => new(Left-delta,Top-delta,Right+delta,Bottom+delta);',f'    public {t} Deflate({scalar} delta) => Inflate(-delta);',f'    public {t} Intersect({t} rhs) => new(CppMath.Max(Left,rhs.Left),CppMath.Max(Top,rhs.Top),CppMath.Min(Right,rhs.Right),CppMath.Min(Bottom,rhs.Bottom));',f'    public {t} Unite({t} rhs) => new(CppMath.Min(Left,rhs.Left),CppMath.Min(Top,rhs.Top),CppMath.Max(Right,rhs.Right),CppMath.Max(Bottom,rhs.Bottom));',f'    public bool Overlaps({t} rhs) {{ if(Right<=rhs.Left||rhs.Right<=Left) return false; if(Bottom<=rhs.Top||rhs.Bottom<=Top) return false; return true; }}',f'    public bool Contains({offset} p) => p.X>=Left && p.X<Right && p.Y>=Top && p.Y<Bottom;',f'    public static bool operator==({t} lhs,{t} rhs) => lhs.Left==rhs.Left && lhs.Top==rhs.Top && lhs.Right==rhs.Right && lhs.Bottom==rhs.Bottom;',f'    public static bool operator!=({t} lhs,{t} rhs) => !(lhs==rhs);',f'    public bool Equals({t} rhs) => this==rhs;',f'    public override bool Equals(object? obj) => obj is {t} rhs && this==rhs;',f'    public override int GetHashCode() => HashCode.Combine(Left,Top,Right,Bottom);']
    other='Rect'+('i' if suffix=='f' else 'f');cast='int' if suffix=='f' else 'float'
    lines += [f'    public static implicit operator {other}({t} v) => new(({cast})v.Left,({cast})v.Top,({cast})v.Right,({cast})v.Bottom);']
    if suffix=='f': lines += ['    public bool IsInfinite() => Left<=float.NegativeInfinity || Top<=float.NegativeInfinity || Right>=float.PositiveInfinity || Bottom>=float.PositiveInfinity;','    public bool IsFinite() => float.IsFinite(Left)&&float.IsFinite(Top)&&float.IsFinite(Right)&&float.IsFinite(Bottom);','    public bool HasNan() => float.IsNaN(Left)||float.IsNaN(Top)||float.IsNaN(Right)||float.IsNaN(Bottom);','    public static Rectf? Lerp(Rectf? a,Rectf? b,float t) { if(!b.HasValue) { if(!a.HasValue) return null; float k=1-t; return new Rectf(a.Value.Left*k,a.Value.Top*k,a.Value.Right*k,a.Value.Bottom*k); } if(!a.HasValue) return new Rectf(b.Value.Left*t,b.Value.Top*t,b.Value.Right*t,b.Value.Bottom*t); var av=a.Value; var bv=b.Value; return new Rectf(av.Left+(bv.Left-av.Left)*t,av.Top+(bv.Top-av.Top)*t,av.Right+(bv.Right-av.Right)*t,av.Bottom+(bv.Bottom-av.Bottom)*t); }']
    lines += ['}', '']
    (root/(t+'.cs')).write_text('\n'.join(lines),encoding='utf-8')
