<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <IsAotCompatible>true</IsAotCompatible>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Optimize>true</Optimize>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../libraries/Sugoi.Data/Sugoi.Data.csproj" />
    <ProjectReference Include="../../libraries/Sugoi.Tasks/Sugoi.Tasks.csproj" />
    <ProjectReference Include="../SugoiFixtures/SugoiFixtures.csproj" />
  </ItemGroup>
</Project>
