using Earthward.Domain;
using System.Globalization;
CultureInfo.CurrentCulture=CultureInfo.InvariantCulture;
CatalogData.Configure(Path.GetFullPath("data/domain"));
var golden=DataMap.Parse(File.ReadAllText("data/domain/golden-reference.json"));
int checks=0,failures=0;
void Check(bool ok,string label){checks++;if(!ok){failures++;Console.Error.WriteLine("DOMAIN_FAIL "+label);}}
void Compare(object? actual,object? expected,string path)
{
 if(expected is DataMap map){Check(actual is DataMap,path+" map");if(actual is DataMap found)foreach(var(k,v)in map)Compare(found.Value(k),v,path+"."+k);return;}
 if(expected is List<object?> list){Check(actual is List<object?>||actual is System.Collections.IEnumerable,path+" array");if(actual is System.Collections.IEnumerable found){var items=found.Cast<object?>().ToList();Check(items.Count==list.Count,path+" count");for(int i=0;i<Math.Min(items.Count,list.Count);i++)Compare(items[i],list[i],path+"["+i+"]");}return;}
 if(DataMap.ValidNumber(expected,-double.MaxValue,double.MaxValue)){double a=DataMap.Number(actual,double.NaN),e=DataMap.Number(expected);Check(double.IsFinite(a)&&Math.Abs(a-e)<=Math.Max(1e-8,Math.Abs(e)*1e-7),path+" "+a+" / "+e);return;}
 Check(Equals(actual,expected),path+" actual="+actual+" expected="+expected);
}
Check(DeepTechnology.Nodes.Count==300,"300 nodes");Check(PerkCatalog.Entries.Count==39,"39 perks");
foreach(var row in golden.List("perk_effects").OfType<DataMap>())Compare(PerkCatalog.Effects(row.S("id"),row.I("level"),PerkCatalog.DefaultSettings),row.Map("effects"),row.S("id")+" level"+row.I("level"));
Compare(PerkCatalog.NeutralModifiers(),golden.Map("perk_neutral"),"neutral");
// Real managed purchase, persistent transactions, inheritance and failure tests.
var funded=new DefenseState{Minerals=1e12,Energy=1e12,Science=1e12,AlienPoints=100000,ResourceCores=100,Wave=120,CompletedWaves=120};funded.SetDefenseReachStage(3);funded.RewardKill("boss",120,3);
var pending=DeepTechnology.Nodes.Select(row=>row.S("id")).ToHashSet();
for(int pass=0;pass<DeepTechnology.Nodes.Count&&pending.Count>0;pass++){int before=pending.Count;foreach(string id in pending.ToList())if(funded.GetGroupStatus(id).B("can_purchase")){Check(funded.PurchaseGroup(id),"actual managed purchase "+id);pending.Remove(id);}if(before==pending.Count)break;}
Check(pending.Count==0,"entire300 actual managed DAG purchase reachable");
Check(funded.PurchaseGroup("K_R00001"),"actual managed independent continuation purchase");
Check(funded.SetAirframe("interceptor",18,-1,"K2"),"select heavy wing");var plan=funded.FactoryAirframePlan("interceptor",18);for(int i=1;i<plan.Count;i++)Check(plan[i].I("berth")==plan[i-1].I("berth")+2,"stable heavy occupancy");
Check(!funded.SetAirframe("interceptor",18,1,"K1"),"cannot select second occupied capacity point");
var fullSnapshot=funded.Serialize();var reopen=new DefenseState();Check(reopen.Restore(DataMap.Parse(fullSnapshot.ToJson())),"full purchasedmanaged save restore");Compare(reopen.DroneStats(),funded.DroneStats(),"purchasedfull restore exact");
var small=new DefenseState();double opening=small.Science;Check(small.PurchaseGroup("K_S01")&&small.Science==opening-4&&small.Minerals==320&&small.Energy==180,"small node onlyscience and one node");Check(small.DeepResearch.Count==1&&!small.HasResearch("K_S02"),"no bundled sibling purchase");Check(small.PurchaseGroup("K_S21")&&small.PurchaseGroup("M_N1"),"missile60 independent of alienpoint randomloot");small.Science=10000;Check(small.PurchaseGroup("I_S03")&&small.PurchaseGroup("I_S23"),"laser prerequisite science node");Check(!small.PurchaseGroup("L_N1"),"laser wave10 gate");small.Wave=10;small.RewardWave(10);Check(small.PurchaseGroup("L_N1"),"laser afterwave10");Check(small.Reset()&&!small.HasResearch("M_N1")&&small.FactoryPerks.KnowsIntel("L1"),"newrun remembersintel but resets paidnodes");small.Science=10000;small.PurchaseGroup("K_S01");small.PurchaseGroup("K_S21");small.PurchaseGroup("M_N1");small.PurchaseGroup("I_S03");small.PurchaseGroup("I_S23");Check(!small.PurchaseGroup("L_N1"),"permanentintel never skips newrun wave10 gate");
var assault=new DefenseState{Science=100000,AlienPoints=100,Wave=24,CompletedWaves=23};assault.RewardKill("boss",3);foreach(string id in new[]{"C_S01","C_S21","C_S02","C_S22","C_S06","C_S26","C_N1","C_A1"})Check(assault.PurchaseGroup(id),"assault prerequisite "+id);Check(!assault.PurchaseGroup("C_G1")&&assault.GetGroupStatus("C_G1").S("lock_reason").Contains("24"),"assault explicit24gate");assault.RewardWave(24);Check(assault.PurchaseGroup("C_G1")&&assault.DroneStats().B("mothership_assault_unlocked"),"wave25 actual assault authorization");
funded.SetCombatSetting("resource_core_upgrade_percent",20);Check(funded.EffectiveResourceCorePercent()==22,"core configurablebase20 plus2points");double mineBase=funded.ResourceFacilityBaseOutputs().N("mine");Check(funded.Build("mine",33),"buildboostedresource");Compare(funded.ResourceFacilityOutput("mine",33),mineBase*2,"boostdoubleactualsiteoutput");Check(funded.UpgradeResourceFacility(33,"mine"),"coreupgradeboostedsite");Compare(funded.ResourceFacilityOutput("mine",33),mineBase*2*1.22,"coreplusboostcomposeonce");funded.Tick(10);var timerCopy=new DefenseState();Check(timerCopy.Restore(DataMap.Parse(funded.Serialize().ToJson())),"boost10seconds snapshot");timerCopy.Tick(10);Compare(timerCopy.ResourceFacilityOutput("mine",33),mineBase*1.22,"boostremaining10 expires");
var carrier=new DefenseState{Wave=40};var unit=new DataMap{["kind"]="carrier",["uid"]=100L,["wave"]=30L,["defense_stage"]=1L};var wallet=carrier.Serialize();Check(carrier.RewardEnemy(unit),"carrierfirstreward");Check(carrier.Minerals==wallet.N("minerals")+22&&carrier.Energy==wallet.N("energy")+9&&carrier.Science==wallet.N("science")+6&&carrier.AlienPoints==0,"carrierold22/9/6/AP0");Check(!carrier.RewardEnemy(unit),"carrierduplicateidempotent");var carrier2=new DefenseState();Check(carrier2.Restore(DataMap.Parse(carrier.Serialize().ToJson()))&&!carrier2.RewardEnemy(unit),"carrierledgerpersists");carrier.RewardEnemy(new(){["kind"]="boss",["uid"]=101L,["wave"]=3L,["spawn_wave"]=3L});Check(carrier.AlienPoints==3,"overlappingbossusesgeneratedwave");
string folder=Path.GetFullPath(Path.Combine(".runtime-tests","domain-permanent-"+Guid.NewGuid().ToString("N")));Directory.CreateDirectory(folder);string profile=Path.Combine(folder,"perks.json");var perks=new FactoryPerks();Check(perks.ProfilePath.Length==0&&!File.Exists(profile),"constructor noIO");Check(perks.LoadProfile(profile),"bindexplicitisolatedprofile");var context=new DataMap{["wave"]=3L,["kinds_unlocked"]=new List<object?>{"interceptor"},["defense_stage"]=0L};var drop=perks.ClaimBossReward("original","wave3",context);Check(drop.B("claimed")&&drop.S("unlocked")=="a_kinetic_core"&&perks.EnergyCores==2,"firstdropdirectaircraftdamage");Check(perks.Upgrade("a_kinetic_core")&&perks.GetLevel("a_kinetic_core")==2&&perks.EnergyCores==0,"firstboss fundsactualpermanentupgrade");Check(perks.Equip("interceptor",-1,0,"a_kinetic_core","aircraft"),"equiprealaircrafttemplate");var fromDisk=new FactoryPerks();Check(fromDisk.LoadProfile(profile)&&fromDisk.GetLevel("a_kinetic_core")==2,"permanentloadinvestment");Check(!fromDisk.ClaimBossReward("original","wave3",context).B("claimed"),"reloadsamehistoricalrewardnoamount");Check(fromDisk.ResetRunSites("fresh")&&fromDisk.GetLevel("a_kinetic_core")==2&&fromDisk.SlotsFor("interceptor",-1,"aircraft")[0]=="a_kinetic_core","newrunkeepslevelsandtemplates");
for(int i=0;i<30;i++)fromDisk.ClaimBossReward("fresh","early"+i,context);Check(!fromDisk.IsUnlocked("a_kinetic_pierce")&&!fromDisk.IsUnlocked("a_laser_crystal"),"earlydroppoolgatesadvancedandunavailabletypes");
var stale=new FactoryPerks();Check(stale.LoadProfile(profile),"secondwriteropenssameversion");Check(fromDisk.ClaimBossReward("fresh","newwrite",context).B("claimed"),"firstwritercommits");var staleBefore=stale.Snapshot();Check(!stale.ClaimBossReward("fresh","stalewrite",context).B("claimed")&&DataMap.Equivalent(stale.Snapshot(),staleBefore),"stalediskwriteratomicrejected");
var blocked=new FactoryPerks();Check(blocked.LoadProfile(profile),"readfailurefixturebind");File.WriteAllText(profile,"corrupt");File.WriteAllText(profile+".bak","also corrupt");var blockedBefore=blocked.Snapshot();Check(!blocked.LoadProfile(profile)&&!blocked.Upgrade("a_kinetic_core")&&!blocked.ResetRunSites("badreset")&&DataMap.Equivalent(blocked.Snapshot(),blockedBefore),"bothcorruptprofilesreadonlyretainmemory");Check(File.ReadAllText(profile)=="corrupt"&&File.ReadAllText(profile+".bak")=="also corrupt","corruptsourcepreservednotreplacedbyblank");
var allPerks=new FactoryPerks();var allMeta=allPerks.Snapshot();allMeta["advanced_unlocked"]=true;allMeta["energy_cores"]=100000L;foreach(string id in allMeta.Map("levels").Keys.ToList())allMeta.Map("levels")[id]=1L;Check(allPerks.ImportSnapshot(allMeta),"all39fixture");Check(allPerks.ResetRunSites("berth"),"bindstableslots");foreach(var frame in AirframeCatalog.Definitions){string kind=frame.S("kind"),id=frame.S("id");Check(allPerks.Definitions("aircraft",kind,id).Count==4,"4applicableperks "+id);foreach(var row in allPerks.Definitions("aircraft",kind,id)){Check(allPerks.Equip(kind,-1,0,row.S("id"),"aircraft",-1,id),"equiptype "+row.S("id"));Check(!DataMap.Equivalent(allPerks.Modifiers(kind,-1,"aircraft",-1,id),PerkCatalog.NeutralModifiers()),"actualexclusiveeffect "+row.S("id"));}allPerks.Equip(kind,-1,0,"","aircraft",-1,id);}
Check(allPerks.Equip("interceptor",-1,0,"a_kinetic_core","aircraft")&&allPerks.Equip("interceptor",18,0,"a_kinetic_pierce","aircraft")&&allPerks.Equip("interceptor",18,0,"a_kinetic_ricochet","aircraft",2),"threelevelinheritance");Check(allPerks.SlotsFor("interceptor",19,"aircraft",2)[0]=="a_kinetic_core"&&allPerks.SlotsFor("interceptor",18,"aircraft",1)[0]=="a_kinetic_pierce"&&allPerks.SlotsFor("interceptor",18,"aircraft",2)[0]=="a_kinetic_ricochet","berthstableandfactoryisolated");
foreach(string mutation in new[]{"unknown_node","fractional_schema","invalid_frame","bad_refund","invalid_flag","unknown_setting","wrong_kind"}){var before=reopen.Serialize();var bad=before.DeepClone();switch(mutation){case "unknown_node":bad.Map("research_state").Map("nodes")["fake"]=1L;break;case "fractional_schema":bad.Map("research_state")["version"]=1.5;break;case "invalid_frame":bad.Map("airframe_selection").Map("templates")["interceptor"]="M3";break;case "bad_refund":bad.Map("research_runtime").List("science_refunds").Add(new DataMap{["amount"]=-1d,["due"]=10d});break;case "invalid_flag":bad.Map("research_flags")["laser_intel"]=1L;break;case "unknown_setting":bad.Map("combat_settings")["fake"]=1L;break;case "wrong_kind":bad.Map("resource_core_upgrades")["5"]=new DataMap{["kind"]="interceptor",["level"]=1L};break;}Check(!reopen.Restore(bad)&&DataMap.Equivalent(reopen.Serialize(),before),"invalidstateatomic "+mutation);}
var vectorMap=new DataMap{["v"]=new Godot.Vector3(1,2,3)};var vectorRound=DataMap.Parse(vectorMap.ToJson());Check(vectorRound.List("v").Count==3&&vectorRound.Vector3("v")==new Godot.Vector3(1,2,3),"GodotvaluearrayJSONboundary");

// Dormant expedition/fleet records must survive the language migration intact.
var retired=new ExpeditionData().Serialize();retired["earth_liberated"]=true;retired.Map("research")["telescope"]=true;retired.Map("telescope_satellite")["deployed"]=true;var moon=retired.Map("sectors").Map("moon");moon["observation_paid"]=true;moon["revealed"]=true;moon["status"]="revealed";moon.List("rewarded_targets").Add("barracks");
var fleet=retired.Map("fleet");fleet["next_id"]=3000003L;fleet.List("orders").Add(new DataMap{["id"]=3000001L,["kind"]="destroyer",["silo_id"]=55L,["duration"]=30d,["elapsed"]=4d,["launch_seconds"]=6d,["transit_seconds"]=18d,["cost"]=new DataMap{["minerals"]=12000d,["energy"]=8000d,["science"]=2000d}});
var ship=new DataMap{["uid"]=3000002L,["kind"]="carrier",["state"]="parked",["silo_id"]=56L,["slot"]=0L,["age"]=25d,["launch_seconds"]=6d,["transit_seconds"]=18d,["clearance"]=24d,["hull_length"]=5d,["launch_origin"]=new List<object?>{0d,0d,24d},["launch_end"]=new List<object?>{0d,0d,26d},["launch_normal"]=new List<object?>{0d,0d,1d},["launch_up"]=new List<object?>{0d,1d,0d},["target"]=new List<object?>{-15.3d,4.275d,11.4d},["position"]=new List<object?>{-15.3d,4.275d,11.4d},["forward"]=new List<object?>{0d,0d,1d},["up"]=new List<object?>{0d,1d,0d}};
fleet.List("ships").Add(ship);
var expedition=new ExpeditionData();Check(expedition.Restore(retired),"dormantfleetwithshipandpaidorderrestores");Check(DataMap.Equivalent(expedition.Serialize(),retired),"retiredfleetresearchsectorssettingspreservedexactly");var invalidRetired=retired.DeepClone();invalidRetired.Map("fleet").List("ships").OfType<DataMap>().Single()["age"]=-1;Check(!expedition.Restore(invalidRetired),"invalidretiredshiprejected");
// A failed permanent write must abort an entire new run / checkpoint switch.
string stateFolder=Path.Combine(folder,"state");Directory.CreateDirectory(stateFolder);var atomic=new DefenseState();Check(atomic.FactoryPerks.LoadProfile(Path.Combine(stateFolder,"perks.json")),"atomicstatescopebind");Check(atomic.FactoryPerks.ResetRunSites(atomic.RunId),"atomiccurrentrunbind");var stateBefore=atomic.Serialize();var metaBefore=atomic.FactoryPerks.Snapshot();Directory.CreateDirectory(atomic.FactoryPerks.ProfilePath+".tmp");var different=stateBefore.DeepClone();different["run_id"]="different-run";different["minerals"]=12345d;Check(!atomic.Restore(different)&&DataMap.Equivalent(atomic.Serialize(),stateBefore)&&DataMap.Equivalent(atomic.FactoryPerks.Snapshot(),metaBefore),"failedmetawriteabortsrunrestoreatomically");Check(!atomic.Reset()&&DataMap.Equivalent(atomic.Serialize(),stateBefore),"failedmetawriteabortsnewrunatomically");Directory.Delete(atomic.FactoryPerks.ProfilePath+".tmp");Check(atomic.Reset(),"atomicnewrunretryaftersafestoragefix");
var maxResource=new DefenseState{ResourceCores=10};Check(maxResource.UpgradeResourceFacility(1,"mine"),"firstrealresourcefacilitycoreupgrade");Check(!maxResource.UpgradeResourceFacility(2,"mine"),"cannotinventsecondfacilitycoreincomefromonebuilding");

WorldScaleChecks.Run(Check, golden, retired);
PatrolCoverageChecks.Run(Check, golden);
ResearchContinuationChecks.Run(Check, golden);
LocalShieldChecks.Run(Check, golden);
CsvCatalogChecks.Run(Check);
Console.WriteLine($"DOMAIN_RESULT {checks-failures} PASS / {failures} FAIL");
return failures==0?0:1;
