using Earthward.Domain;using Earthward.Combat;using Godot;using System.Diagnostics;
internal static class CombatBench
{
 sealed class Surface:ICombatSurface{public List<DataMap> Sites=new();public IReadOnlyList<DataMap> GetFactorySites()=>Sites;public Vector3 SurfaceToSpace(Vector3 n,double a)=>n.Normalized()*(float)(Earthward.WorldScale.EarthRadius+a);public Vector3 SpaceToSurface(Vector3 p)=>p.Normalized();public IReadOnlyList<Vector3> GetOccupiedSurfaceNormals()=>Array.Empty<Vector3>();}
 public static void Run(){var g=new DefenseState{Wave=28,CompletedWaves=27,EarthHp=100,Shield=1e9};g.FactoryPerks.ResetRunSites(g.RunId);var profile=g.FactoryPerks.Snapshot();foreach(string key in profile.Map("levels").Keys.ToArray())profile.Map("levels")[key]=1L;profile["advanced_unlocked"]=true;profile["energy_cores"]=1000000L;g.FactoryPerks.ImportSnapshot(profile);foreach(var row in DeepTechnology.Nodes)g.DeepResearch[row.S("id")]=1L;g.CombatSettings["factory_capacity_multiplier"]=16d;g.Buildings["interceptor"]=10L;g.Buildings["missile"]=10L;g.Buildings["laser"]=10L;g.InvalidateFactoryStats();var surface=new Surface();string[] frames={"K1","K2","K3","M1","M2","M3","L1","L2","L3"};string[][] pairs={new[]{"a_kinetic_pierce","a_kinetic_ricochet"},new[]{"a_k2_dense_fire","a_k2_recovery"},new[]{"a_k3_marked_shot","a_k3_mobile_gun"},new[]{"a_missile_cluster","a_missile_slow"},new[]{"a_m2_dual_zone","a_m2_shock_charge"},new[]{"a_m3_drill_charge","a_m3_escort_guidance"},new[]{"a_laser_refraction","a_laser_erosion"},new[]{"a_l2_charge_memory","a_l2_resonance"},new[]{"a_l3_wide_pulse","a_l3_afterpulse"}};for(int i=0;i<30;i++){string frame=frames[i%9],kind=AirframeCatalog.Definition(frame).S("kind");double angle=Math.Tau*i/30;var normal=new Vector3((float)(.22*Math.Cos(angle)),(float)(.22*Math.Sin(angle)),1).Normalized();surface.Sites.Add(new(){["site_id"]=(long)i+1,["kind"]=kind,["normal"]=normal,["launch_position"]=normal*(Earthward.WorldScale.EarthRadius+.108f),["launch_direction"]=Vector3.Right});if(!g.SetAirframe(kind,i+1,-1,frame))throw new Exception("frame");for(int slot=0;slot<2;slot++)if(!g.FactoryPerks.Equip(kind,i+1,slot,pairs[i%9][slot],"aircraft",-1,frame))throw new Exception("perk "+frame+" "+i+" "+g.FactoryPerks.EquipLockReason(kind,i+1,slot,pairs[i%9][slot],"aircraft",-1,frame));}var b=new Battlefield(g,surface){Active=true};typeof(Battlefield).GetProperty("WaveRunning")!.SetValue(b,true);b.Random.Seed=122;
 void NewDrone(DataMap f){var d=b.SpawnFactoryDrone(f);d["state"]="engaging";d["launch_age"]=1.3;var n=f.Map("site").Vector3("normal");var tangent=n.Cross(Vector3.Up).Normalized();d["space_position"]=(n+tangent*(float)((d.I("patrol_slot")%5-2)*.012)).Normalized()*(float)(Earthward.WorldScale.EarthRadius+1+.025*(d.I("patrol_slot")%4));d["aim_direction"]=n;d["aim_up"]=Vector3.Up;d["velocity"]=Vector3.Zero;b.WorldCache[d.L("uid")]=d.Vector3("space_position");}
 foreach(var f in b.Factories.Values){for(int i=0;i<10;i++)NewDrone(f);f["capacity"]=10*AirframeCatalog.Definition(g.FactoryAirframe(f.S("kind"),f.L("site_id"))).I("capacity_cost");}
 int generation=0,peak=0;void MaintainEnemies(){while(b.Enemies.Count<100){double angle=generation*2.39996323;var n=new Vector3((float)(.21*Math.Cos(angle)),(float)(.21*Math.Sin(angle)),1).Normalized();string role=DefenseWavePlan.RoleOrder[generation%8];var e=b.SpawnEnemy(new[]{"claw","needle","prism","jammer"}.Contains(role)?"scout":"cruiser",new(){["wave"]=28L,["stage"]=0,["role"]=role,["index"]=generation},n*(float)(Earthward.WorldScale.EarthRadius+1.75+.05*(generation%8)))!;double fraction=e.N("energy_max_hp")/e.N("max_hp");e["hp"]=4000d;e["max_hp"]=4000d;e["energy_hp"]=4000*fraction;e["energy_max_hp"]=e["energy_hp"];e["fire"]=.05*(generation%12);generation++;}}
 MaintainEnemies();long firstLoss=0,firstKill=0;var samples=new List<double>();for(int tick=0;tick<480;tick++){var counts=b.Drones.GroupBy(d=>d.L("factory_site_id")).ToDictionary(group=>group.Key,group=>group.Count());foreach(var f in b.Factories.Values)for(int i=0;i<Math.Max(0,10-counts.GetValueOrDefault(f.L("site_id")));i++)NewDrone(f);MaintainEnemies();g.Shield=1e9;long before=Stopwatch.GetTimestamp();b.Step(1d/60);double elapsed=Stopwatch.GetElapsedTime(before).TotalMilliseconds;g.Tick(1d/60);if(tick==119){firstLoss=b.DestroyedDrones;firstKill=g.Kills;}if(tick>=120)samples.Add(elapsed);peak=Math.Max(peak,b.Shots.Count+b.HostileShots.Count);}samples.Sort();var result=new DataMap{["runtime"]=System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription,["cpu"]=System.Environment.GetEnvironmentVariable("PROCESSOR_IDENTIFIER"),["rendering"]="pure managed simulation; no engine scene tree; no rendering",["earth_radius"]=Earthward.WorldScale.EarthRadius,["tick_hz"]=60,["warmup_ticks"]=120,["sample_ticks"]=samples.Count,["allied_population_target"]=300,["enemy_population_target"]=100,["airframes"]=9,["roles"]=8,["p50_ms"]=samples[samples.Count/2],["p95_ms"]=samples[(int)(samples.Count*.95)],["worst_ms"]=samples[^1],["friendly_losses_sample"]=b.DestroyedDrones-firstLoss,["enemy_kills_sample"]=g.Kills-firstKill,["damage_events_total"]=b.NumberSequence,["peak_projectiles"]=peak,["synthetic_population_maintenance"]="refill between measured ticks; not a gameplay-balance pilot"};File.WriteAllText("artifacts/csharp-combat-cpu.json",result.ToJson());Console.WriteLine("MANAGED_COMBAT_CPU "+result.ToJson());}
}


