using Earthward.Domain;using Earthward.Combat;using Godot;using System.Reflection;
internal static class CombatContracts
{
 sealed class Surface:ICombatSurface{public List<DataMap> Sites=new();public double Angle;public IReadOnlyList<DataMap> GetFactorySites()=>Sites;public Vector3 SurfaceToSpace(Vector3 n,double a)=>n.Rotated(Vector3.Up,(float)Angle).Normalized()*(float)(4+a);public Vector3 SpaceToSurface(Vector3 p)=>p.Normalized().Rotated(Vector3.Up,(float)-Angle);public IReadOnlyList<Vector3> GetOccupiedSurfaceNormals()=>Sites.Select(s=>s.Vector3("normal")).ToList();}
 static object? Invoke(Battlefield b,string name,params object?[] args)=>typeof(Battlefield).GetMethod(name,BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic)!.Invoke(b,args);
 public static void Run(Action<bool,string> check){var g=new DefenseState{Wave=28,CompletedWaves=28,Science=1e9,Energy=1e9,Minerals=1e9,AlienPoints=1000};foreach(var row in DeepTechnology.Nodes)g.DeepResearch[row.S("id")]=1L;g.InvalidateFactoryStats();var b=new Battlefield(g);var director=new DefenseCampaignDirector(g,b);b.InvasionDefeated+=director.SyncCampaign;b.RestoreDestroyedFronts(Enumerable.Range(1,7).Select(i=>$"front_{i:00}"));b.StartWave();var mother=b.Motherships.Values.Single();var p=mother.Vector3("space_position");b.MakeShot(p.Normalized()*(p.Length()-.9f),p,1e9,true,0,b.DroneWeaponStats(b.Drones.FirstOrDefault()??new DataMap{["uid"]=0L,["kind"]="missile",["factory_site_id"]=-2000001L,["patrol_slot"]=0}),new(){["weapon_range"]=10d});b.UpdateShots(1);check(director.GetStatus().S("earth_phase")=="ceasefire"&&b.Shots.Count==0&&b.GetDestroyedFronts().Count==8,"last actual missile handles synchronous epoch clear");check(Math.Abs(director.GetStatus().N("ceasefire_remaining")-225)<1e-7,"225 second initial ceasefire");director.Step(224.99);check(!b.WaveRunning&&director.GetStatus().N("ceasefire_remaining")>.009,"no early ceasefire spawn");director.Step(.01);check(b.WaveRunning&&b.PostPlan.N("frontier_radius")==56&&g.DefenseReachStage==1,"first outward cohort44");
 for(int stage=1;stage<=3;stage++){b.UpdateSpawning(30);var mothers=b.Enemies.Where(e=>e.B("post_carrier")&&e.N("hp")>0).ToArray();check(mothers.Length==stage+1,"finite carrier cohort "+stage);check(b.FrontierCohortStatus().I("pending")==0,"pending contains carriers only "+stage);foreach(var m in mothers)b.ApplyEnemyDamage(m,1e12,context:new(){["damage_type"]="explosive"});check(b.FrontierCohortStatus().I("alive")==0&&!b.FixedCycleRunning==false,"all cohort killed waits fixed boundary "+stage);b.AdvanceFixedSchedule(45);check(g.DefenseReachStage==Math.Min(3,stage+1)&&!b.WaveRunning,"clear advances stage at boundary "+stage);director.Step(.01);check(b.PostPlan.N("frontier_radius")==new double[]{88,128,128}[stage-1],"three legs then endless outer radius "+stage);}
 var saved=DataMap.Parse(director.Serialize().ToJson());check(DefenseCampaignDirector.ValidateSnapshot(saved),"active outer director strict snapshot");var bcopy=new Battlefield(g);var dcopy=new DefenseCampaignDirector(g,bcopy);check(dcopy.Restore(saved),"outer director restore");check(bcopy.Random.State==b.Random.State&&bcopy.PostPlan.S("id")==b.PostPlan.S("id"),"outer cohort and RNG roundtrip");var invalid=saved.DeepClone();invalid["earth"]=invalid.Map("earth").DeepClone();invalid.Map("earth")["rng_state"]="not a number";var before=dcopy.Serialize().ToJson();check(!dcopy.Restore(invalid)&&before==dcopy.Serialize().ToJson(),"invalid restore atomic rejection");
 var s=new Surface();foreach(long site in new long[]{18,19})s.Sites.Add(new(){["site_id"]=site,["kind"]="interceptor",["normal"]=site==18?Vector3.Back:Vector3.Right,["launch_position"]=site==18?Vector3.Back*4.108f:Vector3.Right*4.108f,["launch_direction"]=Vector3.Up});var life=new DefenseState{Wave=28,CompletedWaves=28};foreach(var row in DeepTechnology.Nodes)life.DeepResearch[row.S("id")]=1L;life.FactoryPerks.ResetRunSites(life.RunId);var permanent=life.FactoryPerks.Snapshot();foreach(var key in permanent.Map("levels").Keys.ToArray())permanent.Map("levels")[key]=10L;permanent["advanced_unlocked"]=true;permanent["energy_cores"]=1000000L;check(life.FactoryPerks.ImportSnapshot(permanent),"life perk profile");life.InvalidateFactoryStats();check(life.FactoryPerks.Equip("interceptor",18,0,"a_kinetic_core","aircraft",0,"K1"),"unique berth perk");var battle=new Battlefield(life,s){Active=true};var own=battle.SpawnFactoryDrone(battle.Factories[18],0);var other=battle.SpawnFactoryDrone(battle.Factories[19],0);check(battle.DroneWeaponStats(own).N("damage")>battle.DroneWeaponStats(other).N("damage"),"per-life cached override isolated by owner and berth");var reference=battle.DroneWeaponStats(own);life.FactoryPerks.Upgrade("a_kinetic_core");battle.Step(0);check(!ReferenceEquals(reference,battle.DroneWeaponStats(own)),"configuration revision invalidates actor profile");own["state"]="engaging";own["launch_age"]=1.3;own["space_position"]=new Vector3(0,0,5);own["first_fire_at"]=7d;battle.WorldCache[own.L("uid")]=own.Vector3("space_position");double ownDamage=battle.DroneWeaponStats(own).N("damage");long deadUid=own.L("uid");battle.ApplyDroneDamage(own,1e9);check(!battle.IsLiveDrone(deadUid),"dead aircraft removed before explosion");double interval=life.FactorySpawnIntervalForSite("interceptor",18);battle.UpdateFactories(interval);var replacement=battle.Drones.FirstOrDefault(d=>d.L("factory_site_id")==18&&d.I("patrol_slot")==0);check(replacement!=null&&replacement.L("uid")!=deadUid&&Math.Abs(battle.DroneWeaponStats(replacement).N("damage")-ownDamage)<1e-9&&!replacement.ContainsKey("first_fire_at"),"actual replacement preserves berth loadout but new-life precharge");check(battle.Drones.Count(d=>d.L("factory_site_id")==18)==2,"parallel assembly produces two independent berths");
 check(life.SetAirframe("interceptor",18,-1,"K3"),"new heavy airframe production plan");battle.Step(0);check(replacement!=null&&replacement.S("airframe_id")=="K1"&&battle.DroneWeaponStats(replacement).S("airframe_id")=="K1","existing life never retroactively changes hull");s.Angle=.5;Invoke(battle,"RefreshWorldSites");var normal= (Vector3)Invoke(battle,"Home",other)!;check(normal.DistanceTo(Vector3.Right.Rotated(Vector3.Up,.5f))<1e-6,"rotating factory home geometry recomputed outside profile cache");
 if(replacement!=null){replacement["state"]="repairing";replacement["launch_age"]=1.3;replacement["hp"]=replacement.N("max_hp")*.5;replacement["first_fire_at"]=2d;Invoke(battle,"UpdateDroneRepair",replacement,20d);check(replacement.ContainsKey("first_fire_at")&&replacement.N("first_fire_at")==2,"repair does not reset one-life first-fire clock");}
  foreach(string kind in new[]{"interceptor","missile","laser"}){
  var state=new DefenseState();foreach(string id in new[]{"C_G1","C_N2","M_N1","L_N1"})state.DeepResearch[id]=1L;state.InvalidateFactoryStats();var surface=new Surface();surface.Sites.Add(new(){["site_id"]=10L,["kind"]=kind,["normal"]=Vector3.Back,["launch_position"]=Vector3.Back*4.108f,["launch_direction"]=Vector3.Right});var flight=new Battlefield(state,surface){Active=true};flight.Random.Seed=122;var craft=flight.SpawnFactoryDrone(flight.Factories[10]);craft["launch_age"]=1.3;craft["state"]="patrol";
  for(int stage=0;stage<3;stage++){
   double radius=new double[]{56,88,128}[stage];flight.Enemies.Clear();flight.Shots.Clear();craft["space_position"]=new Vector3(0,0,5);craft["target_uid"]=-1L;craft["aim_target_uid"]=-1L;flight.WorldCache[craft.L("uid")]=craft.Vector3("space_position");var enemy=flight.SpawnEnemy("carrier",new(){["wave"]=28L,["stage"]=0,["role"]="rock"},new Vector3(0,0,(float)radius))!;enemy["hp"]=1e8;enemy["max_hp"]=1e8;enemy["energy_hp"]=0d;enemy["energy_max_hp"]=0d;enemy["velocity"]=Vector3.Zero;check(!flight.AssignmentValid(craft,enemy),"old tier cannot acquire "+kind+radius);state.DeepResearch[new[]{"C_A2","C_A3","C_G2"}[stage]]=1L;state.InvalidateFactoryStats();Invoke(flight,"RefreshConfiguration");check(flight.AssignmentValid(craft,enemy),"researched tier acquires "+kind+radius);bool hit=false;double started=flight.Clock;
   for(int frame=0;frame<6000;frame++){typeof(Battlefield).GetProperty("Clock")!.SetValue(flight,flight.Clock+1d/30);flight.UpdateDrones(1d/30);Invoke(flight,"UpdateFiring",1d/30);flight.UpdateShots(1d/30);if(enemy.N("hp")<1e8){hit=true;break;}}
   check(hit&&flight.GetDroneWorldPosition(craft).Length()<=flight.DronePatrolStats(craft).N("action_radius")+.001,"real flight and hit within researched action radius "+kind+radius);Console.WriteLine($"MANAGED_REAL_FLIGHT {kind} radius={radius} seconds={flight.Clock-started:0.00}");
  }
 }
 var fresh1=new Battlefield(new DefenseState());var fresh2=new Battlefield(new DefenseState());check(fresh1.Random.Seed!=fresh2.Random.Seed,"new games randomized independently");ulong seed=fresh1.Random.Seed;fresh1.Random.NextUInt();ulong rngState=fresh1.Random.State;fresh1.ResetBattle();check(fresh1.Random.Seed==seed&&fresh1.Random.State==rngState,"reset preserves current random stream like reference");
 }
}


